version: "3.9"
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      DATABASE_NAME: '${DATABASE_NAME}'
      # So you don't have to use root, but you can if you like
      DATABASE_USERNAME: '${DATABASE_USERNAME}'
      # You can use whatever password you like
      DATABASE_PASSWORD: '${DATABASE_PASSWORD}'
      # Password for root access
      ROOT_PASSWORD: '${ROOT_PASSWORD}'

      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql


  web:
    image: php_web
    build: .
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./app
        target: /var/www/html
    ports:
      - 8100:80
    stdin_open: true
    tty: true
    env_file:
      - .env
    #Ne pas oublier de démarrer APACHE SINON CA NE MARCHE PAS
    command: bash -c 'composer require phpmailer/phpmailer && composer require vlucas/phpdotenv && composer install && service apache2 start && tail -f /dev/null'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
      
# Names our volume
volumes:
  my-db: